name: Collect
on:
  # executed once a week on Sundays at 00:00
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: true

env:
  # time zone
  TZ: Asia/Shanghai

  # github access token
  GIST_PAT: ${{ secrets.GIST_PAT }}

  # github username and gist id, separated by '/'
  GIST_LINK: ${{ secrets.GIST_LINK }}

  # the url to the list of airports that you maintain yourself
  # each line include domain, coupon and invitation code, the domain must be included, and the latter two items are optional
  CUSTOMIZE_LINK: ${{ secrets.CUSTOMIZE_LINK }}

  # include special protocols, such as vless hysteria2 and hysteria
  ENABLE_SPECIAL_PROTOCOLS: ${{ vars.ENABLE_SPECIAL_PROTOCOLS }}

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      # Node.js setup
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or any version you need

      - name: Wait for 5 Seconds
        run: sleep 5

      - name: Install Node.js Dependencies
        run: |
          cd nodefilter
          npm install

      - name: Run Node.js Project
        run: |
          cd nodefilter
          npm start

      - name: Timestamp
        run: date

